### PR TITLE
Upgrade to 16.6.29

### PR DESCRIPTION
**Pull request by DracoBlue**

### CODE REVIEW

**Comment by DracoBlue** [comment]
Still needs some work, because the new version needs java 8

**Comment by DracoBlue** [comment]
Finished.

**Comment by magnetikonline** [comment]
Looks good - thanks for this. Let me validate/confirm it's all working and I'll merge - also need to make a few `README.md` updates.

**Comment by DracoBlue** [comment]
I updated the README.md, too.

**Comment by magnetikonline** [comment]
Committed with https://github.com/magnetikonline/dockerhtml5validator/commit/6ce758492965328d9d72fb61b5f01e6728b9a681 - cheers!

**Comment by DracoBlue** [comment]
Awesomr!

**Pull request closed without merging**
